name-template: 'v$INPUT_VERSION'
tag-template: 'v$INPUT_VERSION'

categories:
  - title: 'Features'
    labels:
      - 'feature'
      - 'enhancement'
      - 'feat'
  - title: 'Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: 'Maintenance'
    labels:
      - 'chore'
      - 'refactor'
      - 'dependencies'
  - title: 'Documentation'
    labels:
      - 'documentation'
      - 'docs'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.

template: |
  ## Changes

  $CHANGES

  ## Contributors

  $CONTRIBUTORS
